language: node_js

node_js:
  - lts

install:
  - npm install

script:
  - npm run lint
  - npm run lint-test
  - npm run cover

after_script: 
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"



